let retainedView=null;
'use strict';
const DATA=JSON.parse(document.getElementById('research-data').textContent),S=DATA.stores;
const $=s=>document.querySelector(s),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dims=['定位客群','空间体验','选品展陈','内容传播','活动社群','会员经营','复合业态','商业模式'],tags=['买手策展','文化社交','馆店联动','专业社群','主题共创'];
const iconSearch='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg>';
const groups={买手策展:'从书刊、图像与版本中理解选书判断。',文化社交:'从对谈、创作者和现场理解文化关系。',馆店联动:'观察展览、出版与书店如何相互连接。',专业社群:'了解书目如何回应学习与专业实践。',主题共创:'探索主题分类、参与和独立出版。'};
const themes=[{id:'content',name:'一本书，如何长成内容',type:'内容传播',desc:'从选书、活动、账号与视觉四条线索，阅读首批十二家书店的内容运营。',legacy:['findings','framework']},{id:'exhibition',name:'看完展览，还可以读什么',type:'选品展陈',desc:'沿着 TPG、ICA 与 Koenig 的案例，寻找展览议题和阅读之间的联系。',stores:['tpg','ica','koenig']},{id:'conversation',name:'让创作者的对话继续发生',type:'活动社群',desc:'从 Tenderbooks、Claire de Rouen 的现有研究进入对谈、书架与现场。',stores:['tenderbooks','claire-de-rouen']}];
const topicItems=S.flatMap(s=>s.topics.map((t,i)=>({id:s.id+'-'+i,name:t,store:s.id,type:'内容选题',desc:s.idea})));
function readStorage(key,fallback){try{return JSON.parse(localStorage.getItem(key))||fallback}catch{return fallback}}
let selected=readStorage('bookstores-v17-selection',[]).filter(id=>S.some(s=>s.id===id)).slice(0,4),lastRoute='',scrollPositions={},toastTimer;
const compareDefault=['选品展陈','内容传播','活动社群'];
function image(key){return DATA.images[key]||''}function thumb(key){return DATA.thumbs?.[key]||image(key)}
function route(){const h=location.hash.slice(1)||'/home';const [path,q='']=h.split('?');return {path,params:new URLSearchParams(q)}}
function url(path,params={}){const q=new URLSearchParams;for(const [k,v]of Object.entries(params))if(v!==''&&v!=null)q.set(k,Array.isArray(v)?v.join(','):v);return '#'+path+(q.size?'?'+q:'')}
function storeURL(s,sec=''){return url('/store/'+s.id,sec?{section:sec}:{})}
function persist(){try{localStorage.setItem('bookstores-v17-selection',JSON.stringify(selected))}catch{}}
function toast(msg){$('#toast').textContent=msg;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').textContent='',3500)}
function addButton(s){return `<button class="btn compare-add ${selected.includes(s.id)?'selected':''}" data-compare="${s.id}" aria-pressed="${selected.includes(s.id)}">${selected.includes(s.id)?'已加入比较':'加入比较'}</button>`}
function card(s){return `<article class="store-card"><a class="cover-link" href="${storeURL(s)}"><img decoding="async" loading="lazy" src="${thumb(s.cover)}" alt="${esc(s.name)} 调研配图"></a><div class="card-body"><div class="card-meta">${esc(s.country)} · ${esc(s.city)} / ${esc(s.type)}</div><h3><a href="${storeURL(s)}">${esc(s.name)}</a></h3><p>${esc(s.subtitle)}</p><div class="tags">${s.tags.map(t=>`<span class="tag">${t}</span>`).join('')}</div><div class="card-bottom"><a href="${storeURL(s)}" class="small">阅读档案</a>${addButton(s)}</div></div></article>`}
function searchForm(q='',local=false){return `<form class="search" data-search="${local?'local':'all'}" role="search">${iconSearch}<input type="search" name="q" value="${esc(q)}" aria-label="${local?'搜索书店':'搜索书店、专题与选题'}" placeholder="${local?'店名、城市、关键词':'搜索书店、城市或研究主题'}"><button class="btn primary-btn" type="submit">搜索</button></form>`}
function head(title,desc='',crumb=''){return `<header class="page-head">${crumb?`<div class="breadcrumb">${crumb}</div>`:''}<h1 tabindex="-1">${title}</h1>${desc?`<p>${desc}</p>`:''}</header>`}
function nav(r){let current=r.path.startsWith('/store')||r.path==='/compare'?'/stores':r.path.startsWith('/topics')?'/topics':r.path.startsWith('/themes')?'/themes':'/home';if(r.path==='/search')current='';$('.primary nav').innerHTML=[['/home','调研首页'],['/stores','书店图鉴'],['/themes','专题阅读'],['/topics','选题手册']].map(([p,n])=>`<a href="${url(p)}" ${current===p?'aria-current="page"':''}>${n}</a>`).join('');let entries=[],context='全球案例 · 筹备思路';
if(r.path.startsWith('/store/')){const s=S.find(s=>r.path.endsWith('/'+s.id));context=s?.name||'书店档案';entries=[['overview','书店概览'],['insights','重点发现'],['dimensions','研究维度'],['related','相关选题'],['sources','图片来源']].map(([id,t])=>[storeURL(s||S[0],id),t,r.params.get('section')===id]);}
else if(current==='/stores'){entries=[[url('/stores'),'全部书店',r.path==='/stores'&&!r.params.get('view')],[url('/stores',{view:'categories'}),'分类浏览',r.params.get('view')==='categories'],[url('/compare',{ids:selected}),'案例比较',r.path==='/compare']];context='按兴趣发现，按维度比较';}
else if(current==='/themes'){entries=[[url('/themes'),'全部专题',!r.params.get('type')],...['内容传播','选品展陈','活动社群'].map(t=>[url('/themes',{type:t}),t,r.params.get('type')===t])];context='从案例走向问题';}
else if(current==='/topics'){entries=[[url('/topics'),'全部选题',!r.params.get('type')],...['内容选题','空间构想','选品思路','活动构想'].map(t=>[url('/topics',{type:t}),t,r.params.get('type')===t])];context='为未来书店积累可能';}
else entries=[['#/home?section=explore','阅读入口'],['#/home?section=featured','精选书店'],['#/search','全站检索']];
$('#secondary').innerHTML=`<span class="context">${esc(context)}</span>`+entries.map(([u,t,active])=>`<a href="${u}" ${active?'aria-current="location"':''}>${t}</a>`).join('');}
function dock(){const d=$('#dock');d.hidden=!selected.length;document.body.classList.toggle('has-dock',!!selected.length);d.innerHTML=`<strong>比较书单 ${selected.length}/4</strong><div class="selected-list">${selected.map(id=>`<button data-compare="${id}" aria-label="移除 ${esc(S.find(s=>s.id===id).name)}">${esc(S.find(s=>s.id===id).name)} ×</button>`).join('')}</div><button class="text-btn" data-clear>清空</button><button class="btn primary-btn" data-open-compare ${selected.length<2?'disabled':''}>${selected.length<2?'再选一家书店':'比较 '+selected.length+' 家书店'}</button>`;document.querySelectorAll('#secondary a').forEach(a=>{if(a.textContent==='案例比较')a.href=url('/compare',{ids:selected})});document.querySelectorAll('[data-compare]').forEach(b=>{if(b.classList.contains('compare-add')){const yes=selected.includes(b.dataset.compare);b.textContent=yes?'已加入比较':'加入比较';b.classList.toggle('selected',yes);b.setAttribute('aria-pressed',yes)}});}
function home(){const hero=S.find(s=>s.id==='libreria');return `<section class="hero"><div><h1 tabindex="-1">全球书店<span>云调研</span></h1><p>从世界各地的书店出发，<br>为未来的书店积累可参考的思路。</p>${searchForm()}<div class="row" style="margin-top:20px"><a href="#/stores" class="btn">翻阅书店图鉴</a><a href="${url('/compare',{ids:['tpg','ica']})}" class="text-btn">试试案例比较</a></div></div><div class="hero-photo"><figure><a href="${storeURL(hero)}"><img fetchpriority="high" decoding="async" width="640" height="480" src="${thumb(hero.cover)}" alt="Libreria 原表调研图片"></a><figcaption><span>Libreria / 主题共创</span><span>进入档案</span></figcaption></figure></div></section><div class="intro-strip"><span>首批收录 12 家英国书店 · 资料观察于 2026.09</span><span>内容运营为首个研究专题，逐步汇入团队成果</span></div><section class="section" id="explore"><div class="section-head"><h2>带着问题，开始阅读</h2></div><div class="home-paths"><article><h3>发现一家书店</h3><p>从城市、类型和经营特征，找到与你关心的问题有关的案例。</p><a href="#/stores">浏览书店图鉴</a></article><article><h3>把不同做法放在一起</h3><p>选择两到四家书店，按相同维度阅读做法与条件。</p><a href="${url('/compare',{ids:['tpg','ica','koenig']})}">比较馆店案例</a></article><article><h3>留住一个值得追问的想法</h3><p>从已有研究中翻阅内容选题，继续积累筹备构想。</p><a href="#/topics">翻阅选题手册</a></article></div></section><section class="section" id="featured"><div class="section-head"><div><h2>从这几家开始</h2><p>三种不同路径：对谈、展览与主题阅读。</p></div><a href="#/stores">查看全部书店</a></div><div class="grid">${['tenderbooks','tpg','libreria'].map(id=>card(S.find(s=>s.id===id))).join('')}</div></section><section class="section"><div class="section-head"><h2>专题阅读</h2><a href="#/themes">全部专题</a></div><div class="home-paths">${themes.map(t=>`<article><h3>${esc(t.name)}</h3><p>${esc(t.desc)}</p><a href="${url('/themes/'+t.id)}">查看已有研究</a></article>`).join('')}</div></section>`}
function available(s,d){if(['内容传播','活动社群','选品展陈'].includes(d))return true;return !!s.notes[d]?.text}
function filtered(p){const q=(p.get('q')||'').trim().toLowerCase(),chosen=(p.get('tags')||'').split(',').filter(Boolean);return S.filter(s=>(!q||JSON.stringify({...s,images:undefined}).toLowerCase().includes(q))&&(!p.get('country')||s.country===p.get('country'))&&(!p.get('type')||s.type===p.get('type'))&&(!p.get('dim')||available(s,p.get('dim')))&&chosen.every(t=>s.tags.includes(t)))}
function selectFilter(key,label,values,p){return `<label>${label}<select data-filter="${key}"><option value="">全部${label}</option>${values.map(v=>`<option ${p.get(key)===v?'selected':''} value="${v}">${v}</option>`).join('')}</select></label>`}
function storesPage(p){if(p.get('view')==='categories')return head('书店图鉴','这些特征可以交叉存在。先选一种兴趣，再按维度继续比较。')+`<div class="category-list">${tags.map(t=>`<article><h2>${t}</h2><p>${groups[t]}</p><div class="row">${S.filter(s=>s.tags.includes(t)).map(s=>`<a href="${storeURL(s)}">${esc(s.name)}</a>`).join('')}</div><p><a href="${url('/stores',{tags:t})}">筛选这类书店</a></p></article>`).join('')}</div>`;
const found=filtered(p),pages=Math.max(1,Math.ceil(found.length/6)),page=Math.min(pages,Math.max(1,parseInt(p.get('page'))||1));let params=Object.fromEntries(p);const selectedTags=(p.get('tags')||'').split(',');return head('书店图鉴','挑选感兴趣的案例，也可以加入比较，看看同一个问题的不同做法。')+`<section class="filters" aria-label="书店筛选"><div class="filter-top">${searchForm(p.get('q')||'',true)}<button class="btn" data-more aria-expanded="${p.get('more')==='1'}">${p.get('more')==='1'?'收起':'更多'}筛选</button></div><div class="filter-fields">${selectFilter('country','地区',['英国'],p)}${selectFilter('type','类型',['独立书店','机构书店'],p)}${p.get('more')==='1'?selectFilter('dim','研究维度',dims,p)+`<fieldset><legend>经营特征 · 可多选，结果需同时符合</legend>${tags.map(t=>`<label class="check"><input type="checkbox" data-tag="${t}" ${selectedTags.includes(t)?'checked':''}>${t}</label>`).join('')}</fieldset>`:''}</div><div class="active-filters">${['q','country','type','dim'].filter(k=>p.get(k)).map(k=>`<button class="filter-chip" data-remove-filter="${k}">${esc(p.get(k))} ×</button>`).join('')}${selectedTags.filter(Boolean).map(t=>`<button class="filter-chip" data-remove-tag="${t}">${t} ×</button>`).join('')}${['q','country','type','dim','tags'].some(k=>p.get(k))?'<button class="text-btn" data-reset>清空筛选</button>':''}</div></section><div class="results-line"><span role="status">找到 ${found.length} 家书店${found.length?' · 显示 '+((page-1)*6+1)+'–'+Math.min(page*6,found.length):''}</span><span>第 ${page} / ${pages} 页</span></div>${found.length?`<div class="grid">${found.slice((page-1)*6,page*6).map(card).join('')}</div><nav class="pagination" aria-label="书店列表分页"><button class="btn" data-page="${page-1}" ${page===1?'disabled':''}>上一页</button>${Array.from({length:pages},(_,i)=>`<button class="btn" data-page="${i+1}" ${page===i+1?'aria-current="page"':''}>${i+1}</button>`).join('')}<button class="btn" data-page="${page+1}" ${page===pages?'disabled':''}>下一页</button></nav>`:`<div class="empty"><h2>暂时没有匹配的书店</h2><p>试试减少筛选条件，或换一个关键词。</p><button class="btn" data-reset>查看全部书店</button></div>`}`}
function sources(s){return `<div class="sources">${s.sources.map(l=>`<a href="${esc(l.url)}" target="_blank" rel="noopener noreferrer">${esc(l.title)}</a>`).join('')}</div>`}
function gallery(s,compact=false){return `<div class="gallery ${compact?'compact':''}">${(compact?s.images.filter(f=>/官网|账号/.test(f.alt)).slice(0,2):s.images).map(f=>`<figure><button class="image-button" data-image="${f.image}" data-caption="${esc(f.caption)}" aria-label="放大查看 ${esc(f.alt)}"><img decoding="async" loading="lazy" src="${thumb(f.image)}" alt="${esc(f.alt)}"></button><figcaption>${esc(f.caption)}${f.url?` · <a href="${esc(f.url)}" target="_blank" rel="noopener">来源网站</a>`:''}</figcaption></figure>`).join('')}</div>`}
function detail(s){return `<header class="page-head"><div class="breadcrumb"><a href="${readStorage('bookstores-v17-list','#/stores')}" data-return-list>书店图鉴</a> / ${esc(s.name)}</div><div class="store-hero" id="overview"><img src="${thumb(s.cover)}" alt=""><div class="identity"><div class="tags"><span class="tag">${s.city} · ${s.country}</span>${s.tags.map(t=>`<span class="tag">${t}</span>`).join('')}</div><div class="row"><div><h1 tabindex="-1">${esc(s.name)}</h1><p>${esc(s.subtitle)}</p></div>${addButton(s)}</div></div></div></header><div class="reading"><div><section class="insight" id="insights"><h2>重点发现</h2><p>${esc(s.insight)}</p><div class="note">研究解读 · 基于首批内容运营资料，适用性仍需结合筹备条件判断。</div></section><section class="detail-section" id="dimensions"><h2>内容运营</h2><div class="op-grid">${Object.entries(s.operations).map(([k,v])=>`<div><h3>${k}</h3><p>${esc(v)}</p></div>`).join('')}</div>${sources(s)}</section><section class="detail-section" id="visual"><h2>视觉风格</h2><div class="visual-layout"><div><h3>${esc(s.tone)}</h3><dl>${Object.entries(s.visual).map(([k,v])=>`<dt>${k}</dt><dd>${esc(v)}</dd>`).join('')}</dl><p class="note">${esc(s.visualBasis)}</p></div>${gallery(s,true)}</div></section><section class="detail-section" id="team"><h2>团队笔记</h2><p class="muted small">保留团队表格原始记录，其中可能包含观察、解读及筹备设想；不作为已核实的经营事实。</p>${Object.entries(s.notes).filter(([k])=>k!=='筹备启发').map(([k,n])=>`<details class="research-note"><summary>${k}<span>${n.text?'原表记录 · '+n.cell:'暂缺资料'}</span></summary><p>${esc(n.text||'当前资料尚未覆盖这个维度。')}</p><p class="note">来源：团队调研表《全球书店云调研 (2)》· 工作表1 · ${n.cell}</p></details>`).join('')}</section><section class="detail-section" id="related"><h2>相关选题</h2><span class="tag">初步构想</span><ul class="topic-list">${s.topics.map((t,i)=>`<li><a href="${url('/topics',{store:s.id,focus:s.id+'-'+i})}">${esc(t)}</a></li>`).join('')}</ul><p>${esc(s.idea)}</p><p class="note">筹备条件：${esc(s.conditions)}</p>${s.notes['筹备启发'].text?`<details class="research-note"><summary>团队筹备启发<span>原表记录</span></summary><p>${esc(s.notes['筹备启发'].text)}</p></details>`:''}<p class="note">资料边界：${esc(s.limits)}</p><div class="sources"><a href="#/themes/content">关联专题：内容运营</a><a href="#/topics">查看选题手册</a></div></section><section class="detail-section" id="sources"><h2>图片来源</h2><p class="note" style="margin:0 0 20px">点击图片查看完整原图。配图用于观察界面与场景，不代表经营效果。</p>${gallery(s)}${sources(s)}</section></div><aside class="side-panel"><h3>阅读这份档案</h3><a href="${storeURL(s,'dimensions')}">内容运营</a><a href="${storeURL(s,'visual')}">视觉风格</a><a href="${storeURL(s,'team')}">团队笔记</a><a href="${storeURL(s,'related')}">相关选题</a><a href="${storeURL(s,'sources')}">图片来源</a><p style="margin-top:20px">资料观察于 2026.09<br>当前研究对象：${esc(s.city)} / ${esc(s.name)}${s.id==='koenig'?'<br>配图含德国品牌官网及账号，不能直接代表伦敦分店运营。':''}</p><button class="btn" data-share style="margin-top:20px">复制档案地址</button></aside></div>`}
function comparisonValue(s,d){if(d==='内容传播')return {basis:'既有研究 · 内容观察与解读',text:Object.entries(s.operations).filter(([k])=>['账号矩阵','内容分布','渠道联动'].includes(k)).map(([k,v])=>k+'：'+v).join('\n\n')+'\n\n视觉调性：'+s.tone};if(d==='选品展陈')return {basis:'既有研究＋团队记录（待核）',text:s.operations['内容分布']+'\n\n团队原表 '+s.notes[d].cell+'：\n'+s.notes[d].text};if(d==='活动社群')return {basis:'既有研究 · 活动样本',text:s.operations['活动节奏']+'\n\n'+s.operations['渠道联动']};const n=s.notes[d];return {basis:n?.text?'团队原表 '+n.cell+' · 未独立核对':'资料不足',text:n?.text||'当前资料尚未覆盖这个维度，不能据此判断该店没有这项业务。'}}
function compareCell(s,d){const v=comparisonValue(s,d),summary=v.text.length>120?v.text.slice(0,120)+'…':v.text;return `<span class="basis">${esc(v.basis)}</span><p>${esc(summary)}</p><details><summary>展开内容与来源</summary><p>${esc(v.text)}</p><div class="source-links"><a href="${storeURL(s,['内容传播','活动社群'].includes(d)?'dimensions':'team')}">查看 ${esc(s.name)} 对应研究</a>${['内容传播','活动社群','选品展陈'].includes(d)?s.sources.slice(0,3).map(l=>`<a href="${esc(l.url)}" target="_blank" rel="noopener">${esc(l.title)}</a>`).join(''):'<span>来源：团队调研表 · 工作表1；原始记录需结合上下文阅读。</span>'}</div></details>`}
function comparePage(p){let ids=(p.get('ids')||selected.join(',')).split(',').filter(id=>S.some(s=>s.id===id));ids=[...new Set(ids)].slice(0,4);const rows=(p.has('dims')?p.get('dims').split(','):compareDefault).filter(d=>dims.includes(d));const stores=ids.map(id=>S.find(s=>s.id===id));return head('把不同做法，放在一起','选择相同维度，阅读差异、条件与待研究的问题。这里不为书店打分。','<a href="#/stores">书店图鉴</a> / 案例比较')+`<div class="row"><a class="btn" href="#/stores">继续选择书店</a>${ids.length>=2?'<button class="btn" data-share>复制比较地址</button>':''}</div>${ids.length<2?'<div class="empty" style="margin-top:24px"><h2>从两家书店开始</h2><p>在书店卡片上点击“加入比较”，最多可以选择四家。</p><a class="btn primary-btn" href="#/stores">去选书店</a></div>':`<div class="comparison-controls" aria-label="比较维度">${dims.map(d=>`<label><input type="checkbox" data-dim="${d}" ${rows.includes(d)?'checked':''}>${d}</label>`).join('')}</div>${!rows.length?'<div class="empty"><h2>选择一个比较维度</h2><p>勾选上方维度，即可查看对应内容。</p></div>':`<div class="compare-scroll" tabindex="0" aria-label="书店比较表，可横向及纵向滚动"><table class="compare-table" style="min-width:${145+stores.length*270}px"><thead><tr><th class="dim-head" scope="col">研究维度</th>${stores.map(s=>`<th scope="col"><img src="${thumb(s.cover)}" alt=""><a href="${storeURL(s)}">${esc(s.name)}</a><div class="small">${s.city} · ${s.type}</div><button class="text-btn" data-remove-column="${s.id}">移除</button></th>`).join('')}</tr></thead><tbody>${rows.map(d=>`<tr><th class="dim-head" scope="row">${d}</th>${stores.map(s=>`<td>${compareCell(s,d)}</td>`).join('')}</tr>`).join('')}</tbody></table></div><div class="compare-mobile">${rows.map(d=>`<section class="mobile-dimension"><h2>${d}</h2>${stores.map(s=>`<article class="mobile-case"><h3><a href="${storeURL(s)}">${esc(s.name)}</a></h3>${compareCell(s,d)}<button class="text-btn" data-remove-column="${s.id}">移除此书店</button></article>`).join('')}</section>`).join('')}</div>`}<p class="compare-note">比较依据为当前收录资料。“团队记录”可能混有筹备设想；缺资料不代表没有业务。每家书店的条件不同，结论需要结合原始来源阅读。</p>`}`}
function themePage(r){const t=themes.find(t=>r.path==='/themes/'+t.id);if(t){const group=t.stores||S.map(s=>s.id);return head(t.name,t.desc,'<a href="#/themes">专题阅读</a> / 已有研究')+`<p class="note">本轮保留已有内容及案例入口，完整专题编排在结构确认后扩展。</p><section class="section"><h2 style="margin-bottom:24px">关联案例</h2><div class="grid">${group.map(id=>card(S.find(s=>s.id===id))).join('')}</div></section>${(t.legacy||[]).map(k=>`<details class="research-note"><summary>${k==='findings'?'阶段发现':'内容框架'}<span>v16 既有研究</span></summary><div class="legacy-text">${esc(DATA.legacy[k].text)}</div></details>`).join('')}`;}const visible=themes.filter(t=>!r.params.get('type')||t.type===r.params.get('type'));return head('专题阅读','从一家书店的做法，走向一个值得继续研究的问题。')+`<p class="note">已有研究入口 · 本轮先确认信息结构，后续扩展完整专题页面。</p><div class="gateway">${visible.map(t=>`<article><span class="tag">${t.type}</span><h2 style="margin-top:16px"><a href="${url('/themes/'+t.id)}">${t.name}</a></h2><p>${t.desc}</p><a href="${url('/themes/'+t.id)}">阅读关联资料</a></article>`).join('')}</div>`}
function topicPage(p){const type=p.get('type'),items=topicItems.filter(t=>(!type||t.type===type)&&(!p.get('store')||t.store===p.get('store')));return head('选题手册','收集值得继续探索的内容与筹备构想。当前选题来自首批内容运营研究。')+`<p class="note">初步构想 · 筹备期参考，尚未形成确定的经营安排。</p>${items.length?`<div class="gateway">${items.map(t=>`<article id="${t.id}"><span class="tag">${t.type}</span><h2 style="margin-top:12px">${esc(t.name)}</h2><p>${esc(t.desc)}</p><a href="${storeURL(S.find(s=>s.id===t.store),'related')}">案例启发：${esc(S.find(s=>s.id===t.store).name)}</a></article>`).join('')}</div>`:'<div class="empty" style="margin-top:24px"><h2>这一类构想，留待继续整理</h2><p>团队表格已保留在对应书店档案中。结构确认后，再将其中的筹备思路整理成选题。</p><a class="btn" href="#/stores">查阅团队笔记</a></div>'}<details class="research-note"><summary>原有内容地图<span>v16 原文保留</span></summary><div class="legacy-text">${esc(DATA.legacy.topics?.text||'')}</div></details><details class="research-note"><summary>原有京东内容<span>筹备参考，非确定安排</span></summary><div class="legacy-text">${esc(DATA.legacy.jd?.text||'')}</div></details>`}
function searchPage(p){const q=(p.get('q')||'').trim(),low=q.toLowerCase(),kind=p.get('kind')||'all';const stores=q?filtered(new URLSearchParams({q})):[],ts=q?themes.filter(t=>JSON.stringify(t).toLowerCase().includes(low)):[],ideas=q?topicItems.filter(t=>JSON.stringify(t).toLowerCase().includes(low)):[];const counts={all:stores.length+ts.length+ideas.length,stores:stores.length,themes:ts.length,topics:ideas.length};return head('全站检索','在书店、专题与选题之间查找。')+searchForm(q)+`<nav class="search-tabs">${[['all','全部'],['stores','书店'],['themes','专题'],['topics','选题']].map(([k,n])=>`<a href="${url('/search',{q,kind:k})}" ${kind===k?'aria-current="page"':''}>${n} ${counts[k]}</a>`).join('')}</nav><div class="search-results">${!q?'<div class="empty"><h2>从一个关键词开始</h2><p>例如：摄影、伦敦、活动、杂志。</p></div>':!counts[kind]?'<div class="empty"><h2>没有找到相关内容</h2><p>请换一个关键词，或切换结果类型。</p></div>':(kind==='all'||kind==='stores'?stores.map(s=>`<article><span class="tag">书店</span><h3><a href="${storeURL(s)}">${esc(s.name)}</a></h3><p>${esc(s.subtitle)} · ${s.city}</p></article>`).join(''):'')+(kind==='all'||kind==='themes'?ts.map(t=>`<article><span class="tag">专题</span><h3><a href="${url('/themes/'+t.id)}">${esc(t.name)}</a></h3><p>${esc(t.desc)}</p></article>`).join(''):'')+(kind==='all'||kind==='topics'?ideas.map(t=>`<article><span class="tag">选题</span><h3><a href="${url('/topics',{store:t.store,focus:t.id})}">${esc(t.name)}</a></h3><p>${esc(t.desc)}</p></article>`).join(''):'')}</div>`}
function render(){const r=route();if(r.path==='/compare'&&r.params.has('ids')){selected=[...new Set(r.params.get('ids').split(','))].filter(id=>S.some(s=>s.id===id)).slice(0,4);persist()}nav(r);let html='';if(r.path==='/home')html=home();else if(r.path==='/stores'){html=storesPage(r.params);try{localStorage.setItem('bookstores-v17-list',JSON.stringify(location.hash||'#/stores'))}catch{}}else if(r.path.startsWith('/store/')){const s=S.find(s=>r.path==='/store/'+s.id);html=s?detail(s):head('没有找到这份档案')+'<a href="#/stores">返回书店图鉴</a>';}else if(r.path==='/compare')html=comparePage(r.params);else if(r.path.startsWith('/themes'))html=themePage(r);else if(r.path==='/topics')html=topicPage(r.params);else if(r.path==='/search')html=searchPage(r.params);else html=head('这个页面暂未收录')+'<a href="#/home">返回首页</a>';$('#app').innerHTML=html;$('#app').classList.remove('fade');void $('#app').offsetWidth;if(!retainedView)$('#app').classList.add('fade');document.title=($('#app h1')?.textContent||'全球书店云调研')+' · 全球书店云调研';dock();const section=r.params.get('section')||r.params.get('focus');if(retainedView){const keep=retainedView;retainedView=null;const panel=document.querySelector('.index-sidebar');if(panel)panel.scrollTop=keep.sidebar;const table=document.querySelector('.compare-scroll');if(table){table.scrollTop=keep.tableY;table.scrollLeft=keep.tableX}const field=[...document.querySelectorAll('[data-facet-key],[data-dim]')].find(x=>keep.key?(x.dataset.facetKey===keep.key&&x.dataset.facetValue===keep.value):x.dataset.dim===keep.dim);field?.focus({preventScroll:true});window.scrollTo({top:keep.y,left:keep.x,behavior:'instant'});}else if(section){requestAnimationFrame(()=>document.getElementById(section)?.scrollIntoView({block:'start'}))}else{const saved=scrollPositions[location.hash];requestAnimationFrame(()=>window.scrollTo(0,saved||0))}lastRoute=location.hash;}
function updateParams(change){const r=route();for(const[k,v]of Object.entries(change)){if(v==null||v==='')r.params.delete(k);else r.params.set(k,v)}location.hash=url(r.path,Object.fromEntries(r.params)).slice(1)}
document.addEventListener('submit',e=>{const f=e.target.closest('[data-search]');if(!f)return;e.preventDefault();const q=new FormData(f).get('q').trim();if(f.dataset.search==='local')updateParams({q,page:1});else location.hash=url('/search',{q}).slice(1)});
document.addEventListener('change',e=>{const el=e.target;if(el.dataset.filter)updateParams({[el.dataset.filter]:el.value,page:1});if(el.dataset.tag){const p=route().params;let t=(p.get('tags')||'').split(',').filter(Boolean);t=el.checked?[...new Set([...t,el.dataset.tag])]:t.filter(x=>x!==el.dataset.tag);updateParams({tags:t.join(','),page:1})}if(el.dataset.dim){const rows=[...document.querySelectorAll('[data-dim]:checked')].map(el=>el.dataset.dim);updateParams({dims:rows.join(',')||'none'})}});
document.addEventListener('click',async e=>{const b=e.target.closest('button,a');if(!b)return;if(b.classList.contains('skip')){e.preventDefault();$('#app').setAttribute('tabindex','-1');$('#app').focus();return}if(b.dataset.compare){const id=b.dataset.compare;if(selected.includes(id))selected=selected.filter(x=>x!==id);else if(selected.length<4)selected.push(id);else{return toast('最多比较四家书店，请先移除一家。')}persist();dock();if(route().path==='/compare')updateParams({ids:selected.join(',')||'none'});}
if(b.hasAttribute('data-clear')){selected=[];persist();dock();if(route().path==='/compare')updateParams({ids:'none'})}
if(b.hasAttribute('data-open-compare'))location.hash=url('/compare',{ids:selected}).slice(1);
if(b.hasAttribute('data-reset'))location.hash='/stores';
if(b.hasAttribute('data-more'))updateParams({more:route().params.get('more')==='1'?'':'1'});
if(b.dataset.removeFilter)updateParams({[b.dataset.removeFilter]:'',page:1});
if(b.dataset.removeTag)updateParams({tags:(route().params.get('tags')||'').split(',').filter(t=>t!==b.dataset.removeTag).join(','),page:1});
if(b.dataset.page)updateParams({page:b.dataset.page});
if(b.dataset.removeColumn){const r=route(),ids=(r.params.get('ids')||selected.join(',')).split(',').filter(id=>id!==b.dataset.removeColumn);selected=selected.filter(id=>id!==b.dataset.removeColumn);persist();dock();updateParams({ids:ids.join(',')||'none'});}
if(b.dataset.image){const d=$('#viewer');$('#viewer-image').src=image(b.dataset.image);$('#viewer-image').alt=b.dataset.caption;$('#viewer-caption').textContent=b.dataset.caption;d.showModal();document.body.style.overflow='hidden';}
if(b.hasAttribute('data-close'))$('#viewer').close();
if(b.hasAttribute('data-share')){try{await navigator.clipboard.writeText(location.href);toast(location.protocol==='file:'?'已复制本地地址；分享给同事时请同时发送 HTML 文件。':'已复制预览地址；当前为本机预览，外部访问需另行发布。')}catch{$('#copy-value').value=location.href;$('#copy-dialog').showModal();$('#copy-value').select();}}
if(b.hasAttribute('data-copy-close'))$('#copy-dialog').close();});
$('#viewer').addEventListener('close',()=>{document.body.style.overflow='';$('#viewer-image').removeAttribute('src')});
window.addEventListener('hashchange',()=>render());window.addEventListener('scroll',()=>{if(lastRoute)scrollPositions[lastRoute]=scrollY;$('.top').classList.toggle('scrolled',scrollY>40)},{passive:true});

// v18: synthesis replaces the parallel raw-note section.
const editorial={
'idea':['以审美选品贯穿书刊与文化商品','区别在于书、服饰与出版项目共享视觉文化语境，账号不仅承担新品通知。','可研究如何把买手判断解释成内容；前提是有真实选书能力和版本资料。'],
'tenderbooks':['围绕创作者与一本书形成栏目','具有名称、主持人与形式的对谈，比零散活动更容易形成连续阅读线索；持续频次仍需核对。','值得研究对谈如何延伸为书页细读、嘉宾书单与现场内容。'],
'claire-de-rouen':['将视觉文化判断延伸至服务','除图书与活动外，已有定制书库等服务入口；服务的收益水平未得到证明。','可探索私人书架、主题书库等方向，需先明确选书能力与服务边界。'],
'artwords':['以杂志与新书组织日常内容','新品、杂志主题与出版社活动之间有直接联系，适合观察选品怎样成为持续内容来源。','可研究主题并置与翻刊栏目，需要稳定书刊供给及编辑解释。'],
'tpg':['沿着展览继续阅读','展览相关与活动相关书目提供直接关联依据；馆方账号与书店账号不能混算。','可研究作品解释与延伸书目，前提是获得展览资料和馆店协作。'],
'ica':['让文化议题连接讨论与出版','机构语境是理解书店的重要条件，不宜把机构整体活动都归于书店。','可研究议题书单如何连接讨论，先确认策展资源与读者需求。'],
'riba':['用专业问题组织书目','专业学习资源与书目构成参考重点；历史内容和实体店状态需区分时间。','可探索分级书目与专家解释，需要专业审核与明确读者阶段。'],
'aa':['从学院研究进入出版阅读','学院、出版与书店的关联具有机构资源条件，不能简单复制活动形式。','可研究课程议题与专题书目，依赖院校或专业研究伙伴。'],
'libreria':['用主题替代单一学科入口','跨学科主题让不同书目相遇，值得比较分类如何改变发现路径。','可探索主题书架与问题书单，需要选书理由而非仅有新颖标签。'],
'november-books':['将旧刊组织成视觉档案','旧书刊的版本、图像与历史语境是重要内容材料，区别于单纯新书推荐。','可研究旧刊细读与图像考察，需要实物、版本信息及可靠背景资料。'],
'good-press':['把独立出版作为参与过程','创作者与出版活动构成研究线索；参与机制比统一视觉模板更值得关注。','可探索小刊物与创作交流，需明确合作、制作与作品使用条件。'],
'koenig':['通过出版目录延伸艺术研究','品牌出版档案与馆店语境值得参考；德国官网样本不能直接代表伦敦分店。','可研究展览、艺术家与出版物之间的索引关系，先区分品牌与门店资源。']};
const oldDetail=detail;
detail=function(s){let html=oldDetail(s);const e=editorial[s.id];html=html.replace('<h2>重点发现</h2>',`<h2>重点发现</h2><h3>${esc(e[0])}</h3><p><strong>区别所在：</strong>${esc(e[1])}</p><p><strong>参考价值：</strong>${esc(e[2])}</p>`);
const start=html.indexOf('<section class="detail-section" id="team">'),end=html.indexOf('<section class="detail-section" id="related">');
const integrated=`<section class="detail-section" id="team"><h2>多维研究</h2><p class="small">按问题整合团队资料。以下为筹备期参考判断，原始记录可展开核对。</p>${['定位客群','空间体验','选品展陈','会员经营','复合业态','商业模式'].map(d=>{const n=s.notes[d];const insight={定位客群:'应将客群与选品、服务一起阅读，不能仅以地段推断真实到访人群。',空间体验:'空间是否值得借鉴，要看它支持什么行为；团队记录中的设计设想不等于对方已采用的做法。',选品展陈:s.operations['内容分布'],会员经营:'会员权益需要与目标读者的持续需求对应；存在权益不代表已经证明留存效果。',复合业态:'关注咖啡或合作业态与阅读之间的关系，不能仅凭共存判断带动消费。',商业模式:'可以研究收入来源与合作方式；利润、成本和坪效仍需独立证据。'}[d];return `<article class="dimension-reading"><h3>${d}</h3><p><strong>研究判断：</strong>${esc(insight)}</p><p><strong>参考方向：</strong>${esc(d==='选品展陈'?e[2]:'结合本店“'+e[0]+'”的特点，继续核对该维度所需的资源与适用条件。')}</p><details><summary>${n?.text?'查看案例记录与依据':'当前资料不足'}</summary><p>${esc(n?.text||'尚不能形成该店在此维度的确定结论。')}</p><p class="small">团队调研表 · 工作表1 · ${n?.cell||''}。原始记录含观察与设想，未独立核实的内容不作经营事实。</p></details></article>`}).join('')}</section>`;
if(start>=0&&end>start)html=html.slice(0,start)+integrated+html.slice(end);
html=html.replaceAll('团队笔记','多维研究');html=html.replace('<h2>图片来源</h2>','<h2>图片来源</h2><details><summary>展开完整图片与来源</summary>').replace('</section></div><aside','</details></section></div><aside');return html};
const oldCompare=comparePage;comparePage=function(p){let html=oldCompare(p);const ids=(p.get('ids')||selected.join(',')).split(',').filter(id=>editorial[id]);if(ids.length<2)return html;const synthesis=`<section class="conclusion"><h2>先看差异</h2>${ids.map(id=>`<p><strong>${esc(S.find(s=>s.id===id).name)}：</strong>${esc(editorial[id][0])}。${esc(editorial[id][1])}</p>`).join('')}<p class="small">以上为单店判断的并置，帮助定位不同路径；并非任意组合都已完成专门的跨店研究。下方按相同维度核对依据。</p></section>`;return html.replace('<div class="comparison-controls"',synthesis+'<div class="comparison-controls"')};
const oldCard=card;card=function(s){return oldCard(s).replace(esc(s.subtitle),esc(editorial[s.id][0]))};
document.addEventListener('error',e=>{if(e.target.tagName==='IMG'){const im=e.target;if(!im.dataset.retried){im.dataset.retried='1';const found=Object.keys(DATA.thumbs||{}).find(k=>DATA.thumbs[k]===im.getAttribute('src'));if(found){im.src=image(found);return}}im.style.display='none';const note=document.createElement('p');note.className='note';note.textContent=(im.alt||'研究配图')+' · 图片暂不可用，请查看来源';im.after(note)}},true);

// v19: authored summaries and JD-oriented proposals, with source details retained.
const priorCompareCell=compareCell;
compareCell=function(s,d){const html=priorCompareCell(s,d);const at=html.indexOf('<details>');const expanded=html.slice(at);return `<p class="comparison-summary">${esc(s.summaries[d]||'暂无可归纳的资料')}</p>${expanded}`};
const proposals=S.flatMap(s=>[
 ...s.topics.map((name,i)=>({id:s.id+'-'+i,name,store:s.id,type:'内容选题',desc:s.topicDetails[i]})),
 ...s.concepts.map((c,i)=>({id:s.id+'-concept-'+i,store:s.id,...c}))
]);
topicItems.splice(0,topicItems.length,...proposals);
topicPage=function(p){const type=p.get('type'),store=p.get('store'),items=proposals.filter(t=>(!type||t.type===type)&&(!store||t.store===store));let page=Math.max(1,parseInt(p.get('page'))||1);const target=items.findIndex(t=>t.id===p.get('focus'));if(target>=0)page=Math.floor(target/12)+1;const pages=Math.max(1,Math.ceil(items.length/12));page=Math.min(page,pages);return head('选题手册','把世界书店的启发，展开为京东书店的内容、空间与阅读体验。')+`<div class="proposal-controls"><span>${items.length} 个构想${type?' · '+esc(type):' · 四种展开方式'}</span>${store?`<a href="${url('/topics',{type})}">查看所有书店</a>`:''}<span>第 ${page} / ${pages} 页</span></div><div class="gateway proposal-grid">${items.slice((page-1)*12,page*12).map(t=>`<article id="${t.id}"><span class="tag">${t.type}</span><h2>${esc(t.name)}</h2><p>${esc(t.desc)}</p><a href="${storeURL(S.find(s=>s.id===t.store),'related')}">案例启发：${esc(S.find(s=>s.id===t.store).name)}</a></article>`).join('')}</div>${pages>1?`<nav class="pagination" aria-label="选题分页"><button class="btn" data-topic-page="${page-1}" ${page===1?'disabled':''}>上一页</button>${Array.from({length:pages},(_,i)=>`<button class="btn" data-topic-page="${i+1}" ${i+1===page?'aria-current="page"':''}>${i+1}</button>`).join('')}<button class="btn" data-topic-page="${page+1}" ${page===pages?'disabled':''}>下一页</button></nav>`:''}`};
const priorDock=dock;dock=function(){priorDock();const el=$('#dock');$('#app').before(el);const r=route();el.hidden=!selected.length||!['/stores','/compare'].includes(r.path);document.body.classList.remove('has-dock');const navLink=[...document.querySelectorAll('#secondary a')].find(a=>a.textContent.startsWith('案例比较'));if(navLink){navLink.textContent='案例比较'+(selected.length?' ('+selected.length+')':'');navLink.href=url('/compare',{ids:selected})}};
const priorRender=render;render=function(){priorRender();document.querySelectorAll('#app .compare-note').forEach(n=>n.remove());document.querySelectorAll('#app .note').forEach(n=>{if(!n.closest('details')&&/研究解读 ·|本轮|本次|原始记录|以下为|筹备期参考|资料边界|未形成|不代表|资料观察/.test(n.textContent)){if(n.textContent.startsWith('资料边界')){const det=document.createElement('details');det.className='research-note';det.innerHTML='<summary>资料说明</summary>';n.before(det);det.append(n)}else n.remove()}});document.querySelectorAll('#app .small').forEach(n=>{if(!n.closest('details')&&/保留团队|按问题整合团队/.test(n.textContent))n.remove()});
// Add the new JD concepts to each store's related reading without duplicating details.
if(route().path.startsWith('/store/')){const s=S.find(s=>route().path.endsWith('/'+s.id));const section=$('#related');if(s&&section){const link=document.createElement('p');link.innerHTML=`<a href="${url('/topics',{store:s.id})}">展开 ${esc(s.name)} 的全部京东构想</a>`;section.append(link)}}
};
document.addEventListener('click',e=>{const b=e.target.closest('[data-topic-page]');if(b)updateParams({page:b.dataset.topicPage,focus:''})});

// v20: matching facet navigation for the store atlas and topic handbook.
const storeTypes=['艺术·摄影·时尚出版','美术馆·机构店','专业·学院店','策展综合店','独立出版·制作'];
const atlasType={idea:0,tenderbooks:0,'claire-de-rouen':0,artwords:0,'november-books':0,tpg:1,ica:1,koenig:1,riba:2,aa:2,libreria:3,'good-press':4};
const themeNames=['艺术科技','视觉文化','城市生活','建筑空间','独立出版','展览阅读','创作者对谈','生活美学'];
const topicThemes={
 idea:[['艺术科技','视觉文化'],['视觉文化','生活美学'],['视觉文化'],['视觉文化','生活美学'],['视觉文化']],
 tenderbooks:[['视觉文化','生活美学'],['创作者对谈','独立出版'],['独立出版','展览阅读'],['独立出版','创作者对谈'],['创作者对谈']],
 'claire-de-rouen':[['创作者对谈','生活美学'],['视觉文化','生活美学'],['创作者对谈','建筑空间'],['建筑空间','生活美学'],['创作者对谈','视觉文化']],
 artwords:[['生活美学','视觉文化'],['生活美学','视觉文化'],['视觉文化'],['生活美学','视觉文化'],['独立出版','视觉文化']],
 tpg:[['展览阅读','艺术科技'],['视觉文化','展览阅读'],['展览阅读','建筑空间'],['视觉文化'],['展览阅读','视觉文化']],
 ica:[['艺术科技','生活美学'],['艺术科技','独立出版'],['展览阅读','建筑空间'],['艺术科技','展览阅读'],['艺术科技','创作者对谈']],
 riba:[['建筑空间'],['建筑空间'],['建筑空间'],['建筑空间'],['建筑空间','生活美学']],
 aa:[['城市生活','独立出版'],['建筑空间','独立出版'],['建筑空间','展览阅读'],['建筑空间','城市生活'],['建筑空间','创作者对谈']],
 libreria:[['城市生活','视觉文化'],['生活美学'],['城市生活','建筑空间'],['生活美学'],['生活美学','城市生活']],
 'november-books':[['视觉文化'],['城市生活','独立出版'],['视觉文化','建筑空间'],['视觉文化','独立出版'],['城市生活','独立出版']],
 'good-press':[['城市生活','独立出版'],['独立出版'],['城市生活','独立出版'],['城市生活','独立出版'],['城市生活','独立出版']],
 koenig:[['展览阅读'],['独立出版','展览阅读'],['展览阅读','建筑空间'],['展览阅读','视觉文化'],['独立出版','创作者对谈']]
};
proposals.forEach(t=>{const pos=t.id.includes('-concept-')?2+Number(t.id.split('-concept-')[1]):Number(t.id.split('-').pop());t.themes=topicThemes[t.store]?.[pos]||[]});
const facetValues=p=>[...new Set(String(p||'').split(',').filter(Boolean))];
function atlasMatch(s,p,omit=''){const q=(p.get('q')||'').trim().toLowerCase();return (!q||JSON.stringify({...s,images:undefined}).toLowerCase().includes(q))&&
 (omit==='tags'||!facetValues(p.get('tags')).length||facetValues(p.get('tags')).some(t=>s.tags.includes(t)))&&
 (omit==='types'||!facetValues(p.get('types')).length||facetValues(p.get('types')).includes(storeTypes[atlasType[s.id]]))&&
 (omit==='dims'||!facetValues(p.get('dims')).length||facetValues(p.get('dims')).some(t=>available(s,t)))&&
 (omit==='countries'||!facetValues(p.get('countries')).length||facetValues(p.get('countries')).includes(s.country));}
function ideaMatch(t,p,omit=''){const q=(p.get('q')||'').trim().toLowerCase();return (!q||[t.name,t.desc,t.type,...t.themes,S.find(s=>s.id===t.store)?.name].join(' ').toLowerCase().includes(q))&&
 (omit==='themes'||!facetValues(p.get('themes')).length||facetValues(p.get('themes')).some(v=>t.themes.includes(v)))&&
 (omit==='type'||!facetValues(p.get('type')).length||facetValues(p.get('type')).includes(t.type))&&
 (omit==='store'||!facetValues(p.get('store')).length||facetValues(p.get('store')).includes(t.store));}
function facetGroup(title,key,values,p,count,label=x=>x){const selected=facetValues(p.get(key));return `<fieldset class="facet-group"><legend>${title}</legend>${values.map(v=>{const c=count(v),yes=selected.includes(v);return `<label class="facet-option ${!c&&!yes?'unavailable':''}"><input type="checkbox" data-facet-key="${key}" data-facet-value="${esc(v)}" ${yes?'checked':''} ${!c&&!yes?'disabled':''}><span>${esc(label(v))}</span><span class="facet-count">${c}</span></label>`}).join('')}</fieldset>`}
function chips(p,keys,kind){const labels={q:'搜索',tags:'特征',types:'类型',dims:'维度',countries:'地区',themes:'主题',type:'类型',store:'书店'};const entries=keys.flatMap(k=>(k==='q'?(p.get(k)?[p.get(k)]:[]):facetValues(p.get(k))).map(v=>({k,v})));if(!entries.length)return '';return `<div class="index-chips">${entries.map(({k,v})=>`<button class="filter-chip" data-facet-remove="${k}" data-facet-value="${esc(v)}">${labels[k]}：${esc(k==='store'?S.find(s=>s.id===v)?.name||v:v)} <span aria-hidden="true">×</span></button>`).join('')}<a href="${url(kind==='stores'?'/stores':'/topics')}" class="clear-index">清空全部</a></div>`}
function indexSearch(q,kind){return `<form class="search index-search" data-index-search="${kind}" role="search">${iconSearch}<input name="q" type="search" value="${esc(q||'')}" aria-label="${kind==='stores'?'搜索书店':'搜索选题'}" placeholder="${kind==='stores'?'搜索书店名称、城市、研究主题或关键词':'搜索选题、主题或参考书店'}"><button class="btn primary-btn" type="submit">搜索</button></form>`}
function sortControl(p,kind){return `<label class="index-sort">排序<select data-index-sort><option value="default" ${!p.get('sort')||p.get('sort')==='default'?'selected':''}>${kind==='stores'?'调研顺序':'主题顺序'}</option><option value="name" ${p.get('sort')==='name'?'selected':''}>名称排序</option>${kind==='stores'?`<option value="city" ${p.get('sort')==='city'?'selected':''}>城市排序</option>`:`<option value="store" ${p.get('sort')==='store'?'selected':''}>参考书店</option>`}</select></label>`}
function indexPager(page,pages){if(pages<2)return '';return `<nav class="pagination" aria-label="结果分页"><button class="btn" data-index-page="${page-1}" ${page===1?'disabled':''}>上一页</button>${Array.from({length:pages},(_,i)=>`<button class="btn" data-index-page="${i+1}" ${i+1===page?'aria-current="page"':''}>${i+1}</button>`).join('')}<button class="btn" data-index-page="${page+1}" ${page===pages?'disabled':''}>下一页</button></nav>`}
function normalizeAtlasParams(p){const q=new URLSearchParams(p);if(q.get('type')&&!q.get('types'))q.set('types',(q.get('type')==='机构书店'?storeTypes.slice(1,3):[storeTypes[0],storeTypes[3],storeTypes[4]]).join(','));if(q.get('dim')&&!q.get('dims'))q.set('dims',q.get('dim'));if(q.get('country')&&!q.get('countries'))q.set('countries',q.get('country'));['type','dim','country'].forEach(k=>q.delete(k));return q}
let mobileIndexOpen=false;
function indexSidebarOpen(){return matchMedia('(min-width:801px)').matches||mobileIndexOpen}
const previousAtlas=storesPage;
storesPage=function(p){const query=normalizeAtlasParams(p);
 const found=S.filter(s=>atlasMatch(s,query));const sort=query.get('sort');if(sort==='name')found.sort((a,b)=>a.name.localeCompare(b.name,'en'));if(sort==='city')found.sort((a,b)=>a.city.localeCompare(b.city,'zh')||a.name.localeCompare(b.name));const pages=Math.max(1,Math.ceil(found.length/6)),page=Math.min(pages,Math.max(1,Number(query.get('page'))||1));
 const aside=facetGroup('经营特征 · 可多选','tags',tags,query,v=>S.filter(s=>atlasMatch(s,query,'tags')&&s.tags.includes(v)).length)+facetGroup('书店类型','types',storeTypes,query,v=>S.filter(s=>atlasMatch(s,query,'types')&&storeTypes[atlasType[s.id]]===v).length)+facetGroup('研究维度','dims',dims,query,v=>S.filter(s=>atlasMatch(s,query,'dims')&&available(s,v)).length)+facetGroup('国家地区','countries',['英国'],query,v=>S.filter(s=>atlasMatch(s,query,'countries')&&s.country===v).length);
 return head('书店图鉴','从经营特征与研究兴趣出发，发现书店，也看见不同做法之间的联系。')+`<div class="index-layout"><details class="index-sidebar" ${indexSidebarOpen()?'open':''}><summary>分类筛选</summary><div class="sidebar-content">${aside}<p class="facet-help">同组多选为“任一符合”，不同组同时筛选。</p></div></details><div class="index-results">${indexSearch(query.get('q'),'stores')}<div class="index-toolbar"><span role="status">共 <strong>${found.length}</strong> 家书店 · 第 ${page} / ${pages} 页</span>${sortControl(query,'stores')}</div>${chips(query,['q','tags','types','dims','countries'],'stores')}${found.length?`<div class="grid atlas-grid">${found.slice((page-1)*6,page*6).map(s=>{let h=card(s);h=h.replace(esc(s.type),esc(storeTypes[atlasType[s.id]]));return h}).join('')}</div>${indexPager(page,pages)}`:`<div class="empty"><h2>没有符合这些条件的书店</h2><p>减少筛选条件，或换个关键词继续发现。</p><a class="btn" href="#/stores">清空筛选</a></div>`}</div></div>`};
topicPage=function(p){const items=proposals.filter(t=>ideaMatch(t,p));const sort=p.get('sort')||'default';if(sort==='name')items.sort((a,b)=>a.name.localeCompare(b.name,'zh'));else if(sort==='store')items.sort((a,b)=>S.find(s=>s.id===a.store).name.localeCompare(S.find(s=>s.id===b.store).name));else items.sort((a,b)=>themeNames.indexOf(a.themes[0])-themeNames.indexOf(b.themes[0]));const pages=Math.max(1,Math.ceil(items.length/12));let page=Math.min(pages,Math.max(1,Number(p.get('page'))||1));const focus=items.findIndex(t=>t.id===p.get('focus'));if(focus>=0)page=Math.floor(focus/12)+1;
 const aside=facetGroup('研究主题 · 可多选','themes',themeNames,p,v=>proposals.filter(t=>ideaMatch(t,p,'themes')&&t.themes.includes(v)).length)+facetGroup('构想类型','type',['内容选题','空间构想','选品思路','活动构想'],p,v=>proposals.filter(t=>ideaMatch(t,p,'type')&&t.type===v).length)+facetGroup('参考书店','store',S.map(s=>s.id),p,v=>proposals.filter(t=>ideaMatch(t,p,'store')&&t.store===v).length,v=>S.find(s=>s.id===v).name);
 return head('选题手册','先选一个关心的主题，再探索它可以成为怎样的内容、空间、选品与活动。')+`<div class="index-layout"><details class="index-sidebar" ${indexSidebarOpen()?'open':''}><summary>主题索引</summary><div class="sidebar-content">${aside}<p class="facet-help">一项构想可关联多个主题。主题之间可多选。</p></div></details><div class="index-results">${indexSearch(p.get('q'),'topics')}<div class="index-toolbar"><span role="status">共 <strong>${items.length}</strong> 个构想 · 第 ${page} / ${pages} 页</span>${sortControl(p,'topics')}</div>${chips(p,['q','themes','type','store'],'topics')}${items.length?`<div class="gateway proposal-grid indexed-topics">${items.slice((page-1)*12,page*12).map(t=>`<article id="${t.id}"><div class="tags">${t.themes.map(th=>`<a class="tag theme-link" href="${url('/topics',{themes:th,type:p.get('type')||''})}">${th}</a>`).join('')}<span class="topic-kind">${t.type}</span></div><h2>${esc(t.name)}</h2><p>${esc(t.desc)}</p><a href="${storeURL(S.find(s=>s.id===t.store),'related')}">案例启发：${esc(S.find(s=>s.id===t.store).name)}</a></article>`).join('')}</div>${indexPager(page,pages)}`:`<div class="empty"><h2>试试另一种主题组合</h2><p>当前没有匹配构想，可取消部分条件继续查找。</p><a class="btn" href="#/topics">查看全部选题</a></div>`}</div></div>`};
document.addEventListener('change',e=>{const x=e.target;if(x.dataset.facetKey){const key=x.dataset.facetKey,value=x.dataset.facetValue;let values=facetValues((route().path==='/stores'?normalizeAtlasParams(route().params):route().params).get(key));values=x.checked?[...new Set([...values,value])]:values.filter(v=>v!==value);updateParams({[key]:values.join(','),page:1,focus:'',view:''})}if(x.hasAttribute('data-index-sort'))updateParams({sort:x.value,page:1,focus:''})});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.facetRemove){const key=b.dataset.facetRemove,value=b.dataset.facetValue;updateParams({[key]:key==='q'?'':facetValues((route().path==='/stores'?normalizeAtlasParams(route().params):route().params).get(key)).filter(v=>v!==value).join(','),page:1,focus:''})}if(b.dataset.indexPage)updateParams({page:b.dataset.indexPage,focus:''})});
document.addEventListener('submit',e=>{const f=e.target.closest('[data-index-search]');if(!f)return;e.preventDefault();e.stopImmediatePropagation();updateParams({q:new FormData(f).get('q').trim(),page:1,focus:''})},true);

// Preserve mobile filter expansion across selection and viewport changes.
document.addEventListener('toggle',e=>{if(e.target.matches?.('.index-sidebar')&&!matchMedia('(min-width:801px)').matches)mobileIndexOpen=e.target.open},true);
matchMedia('(min-width:801px)').addEventListener('change',e=>{const sidebar=document.querySelector('.index-sidebar');if(sidebar)sidebar.open=e.matches||mobileIndexOpen});
const indexUpdateParams=updateParams;
updateParams=function(change){if(route().path==='/stores'){const p=normalizeAtlasParams(route().params);for(const [k,v]of Object.entries(change)){if(v===''||v==null)p.delete(k);else p.set(k,v)}location.hash=url('/stores',Object.fromEntries(p));return}indexUpdateParams(change)};

// v21: retain both scrolling surfaces during repeated filtering.
document.addEventListener('change',e=>{if(!e.target.matches('[data-facet-key],[data-dim]'))return;const panel=document.querySelector('.index-sidebar'),table=document.querySelector('.compare-scroll');retainedView={y:window.scrollY,x:window.scrollX,sidebar:panel?.scrollTop||0,tableY:table?.scrollTop||0,tableX:table?.scrollLeft||0,key:e.target.dataset.facetKey,value:e.target.dataset.facetValue,dim:e.target.dataset.dim};},true);
const v20Dock=dock;
dock=function(){v20Dock();const el=document.querySelector('#dock');el.classList.add('bottom-comparison');document.body.classList.toggle('bottom-comparison-visible',!el.hidden);el.querySelectorAll('.selected-list button').forEach(b=>{const s=S.find(s=>s.id===b.dataset.compare);if(s)b.innerHTML=`<img src="${thumb(s.cover)}" alt=""><span>${esc(s.name)}</span><span aria-hidden="true">×</span>`});};
const v20Compare=comparePage;
comparePage=function(p){let h=v20Compare(p);h=h.replace('<div class="comparison-controls" aria-label="比较维度">','<div class="comparison-controls" aria-label="比较维度"><strong>比较维度</strong>');const marker='</div><div class="compare-scroll"';h=h.replace(marker,'<button class="btn compare-expand" data-expand-comparison aria-expanded="false">展开明细与来源</button>'+marker);return h};
document.addEventListener('click',e=>{const b=e.target.closest('[data-expand-comparison]');if(!b)return;const open=b.getAttribute('aria-expanded')!=='true';document.querySelectorAll('.compare-table details,.compare-mobile details').forEach(d=>d.open=open);b.setAttribute('aria-expanded',String(open));b.textContent=open?'收起明细与来源':'展开明细与来源'});

render();
